### ISSUE TITLE
Update issue - http://192.168.1.xxx/hostname.json 404

### ISSUE THREAD

**Issue by Streametch** [enjoyneering/tthRelay#1]
После обновления по воздуху, через меню tthrelay из версии 4.0.6 -> 4.0.7 появилась ошибка 404 на hostname.json. Данная ошибка всплывает при загрузке каждой страницы. Так же смена Hostname в настройках не изменяется, настройка запоминается, но на всех страницах по прежнему tthRelay.  Есть ли смысл повторять обновление? Для исправления данной ошибки можно ли прошиться по воздуху?

**Comment by Streametch** [comment]
Прошил заново через меню tthrelay (fs и fw) - ошибка осталась.

**Comment by enjoyneering** [comment]
там на странице software update есть предостережение и оно там не для украшательства - **Warning: Clear browser cache after update**

Для ускорения работы сервера, в проекте используются очень агрессивны настройки кеширования HTML и JavaScript. Браузер только первый раз читает эти файлы с tthRelay и сохраняет себе в кеш. Про последующие обновление fs_latest.bin он ничего не знает и вместо новых HTML и JavaScript, с вероятностью 100%, будет тянуть старые из кеша. Обязательно чистите кеш после обновления файловой системы.

**Comment by Streametch** [comment]
Да, но в режиме инкогнито браузера старый кеш не учитывается, да и 404 ошибка действительно присутствует, файл hostname.json не выдаёт 
![image](https://user-images.githubusercontent.com/7738904/189361677-1586c36d-5c74-403b-8601-56cd04ca8cb9.png)

**Comment by enjoyneering** [comment]
странно. сегодня проверю. спасибо

**Comment by enjoyneering** [comment]
Обновил до v4.1.0. Проверьте пожалуйста.

**Comment by Streametch** [comment]
Обновился, проблемы больше нет. Спасибо!
